### ISSUE TITLE
How to train the model?

### ISSUE THREAD

**Issue by LiuJoffrey** [mgharbi/demosaicnet#1]
Hi, 
I would like to know how to train the model without using the pretrained model you provided. Could you provide me with training method or training code? 

Thank you so much

**Comment by mgharbi** [comment]
Hi, I currently do not plan to write training code for this pretrained model in PyTorch, although it should be relatively easy to write your own. The original implementation, with training code in Caffe, can be found here: https://github.com/mgharbi/demosaicnet_caffe
