### ISSUE TITLE
Questions regarding scripts

### ISSUE THREAD

**Issue by PascalBACCHUS** [mgharbi/demosaicnet#10]
Hello Michaël,

First of all, thank you for your work.

Is your script `train.py` usable? I saw an old Issue where you said weren't planning to write it but uploaded something a year later. I just want to know if this script is a rough draft of what should be a training script, and needs further work on it.

Also, how is the added noise managed in your BayerDemosaick class? I didn't see any mention of it.

Thank you

**Comment by mgharbi** [comment]
I have not had the time to test the train script unfortunately, but it should be a good starting point. 

I have not ported the noise input to PyTorch, see earlier Caffe implementation for that https://github.com/mgharbi/demosaicnet_caffe
