### ISSUE TITLE
where is the noise level for denoising?

### ISSUE THREAD

**Issue by zhengtianyu1996** [mgharbi/demosaicnet#11]
Hi, thank you for your brilliant job!

I am wondering where is the noise level, the paper's figure shows that the input of the network should be a 4-channel image with a noise level. Or maybe the demo code and default checkpoint just do demosaicking, I need to modify the code myself to denoise?

Thank you so much : )

**Comment by mgharbi** [comment]
Hi,

Yes, unfortunately I have not ported the joint demosaick/denoise models to PyTorch. An earlier implementation can be found here for reference https://github.com/mgharbi/demosaicnet_caffe
