### ISSUE TITLE
The evaluation result of the released weight for bayer is different from those from the paper.

### ISSUE THREAD

**Issue by xhchen10** [mgharbi/demosaicnet#12]
Hi! Thanks for sharing this impressive work.

I evaluate demosaicnet with the released weight on the Moire and HDRVDP dataset. The results are 36.03 and 33.63 dB on Moire and HDRVDP respectively. However, the corresponding results from the paper are 37.0 and 34.3 dB.

I'd like to ask if my testing results are correct.

Best.

**Comment by mgharbi** [comment]
For the paper, we evaluate the Caffe implementation of the model (with [this code](https://github.com/mgharbi/demosaicnet_caffe/blob/ba4e77c50e46619b85cb871d740c6a39f12c0f25/bin/demosaick#L44) I believe). The model weights in PyTorch were converted from caffe. The PyTorch output should match, so I believe your numbers look reasonable.

The discrepancy might come from different boundary size. In our evaluation we cropped a few pixel on the edges to ignore possible boundary artefacts in the output or baselines. I do not remember the exact crop size.
