### ISSUE TITLE
Vertical stripe CFA

### ISSUE THREAD

**Issue by makejohn** [mgharbi/demosaicnet#14]
Hello, I got a Vertical stripe CFA, which looks like
[[R G B R G B R G B]
 [R G B R G B R G B]
 [R G B R G B R G B]
 [R G B R G B R G B]]
Can I use this project, I'm not familiar with Deep learning, want to know if this kind of methods can be used in this kind of CFA

**Comment by mgharbi** [comment]
You can, but you will have to train a new model for this specific pattern. Check how we do it [here](https://github.com/mgharbi/demosaicnet/blob/959e9d1630976b421d5af5e35b2e2a01f5630e5c/demosaicnet/mosaic.py#L9).
