### ISSUE TITLE
 Request for Code on Mining Hard Patches in the Fourier Domain

### ISSUE THREAD

**Issue by tuotuo-glacier** [mgharbi/demosaicnet#16]
I’ve been studying your paper Deep Joint Demosaicking and Denoising and am very interested in the method for mining hard patches in the Fourier domain. I noticed that the specific code related to this, particularly the implementation involving the gain map threshold for marking aliased patches, isn't available in the repository.
Could you please share the code? I would be extremely grateful for your consideration of my request.

**Comment by mgharbi** [comment]
I found this code in our old codebase, this should be what you need. It'll likely need some changes/fixes:

https://gist.github.com/mgharbi/57d81c5e166bb625ba52629760a9da2a

**Comment by tuotuo-glacier** [comment]
Dear Dr. Mgharbi,

Thank you for sharing the code! I appreciate your help and will review it carefully. If I run into any issues, I’ll reach out.

Best regards,





#0000FF
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mgharbi/demosaicnet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月9日(星期一) 凌晨1:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mgharbi/demosaicnet]  Request for Code on Mining Hard Patches in the Fourier Domain (Issue #16)





 
Closed #16 as completed.
