### ISSUE TITLE
Is it correct that the output image is not the same size as the input?

### ISSUE THREAD

**Issue by acboyty** [mgharbi/demosaicnet#2]
Hi!
When I run the demo code, I found the size of output image is 66 x 66(bayer) and 104 x 104(xtrans) while the input is 128 x 128, and boders of the image are lost. I think it inconsistent with the model in your paper _Deep joint demosaicking and denoising_, in which the input and output are both 128 x 128.
I am wondering if it is correct?
test_input.png:
![test_input](https://user-images.githubusercontent.com/47970756/77725165-b8894880-702f-11ea-9205-851c3703bf93.png)
bayer_result.png:
![bayer_result](https://user-images.githubusercontent.com/47970756/77725185-c17a1a00-702f-11ea-9bc3-c90b016c285c.png)
xtrans_result.png
![xtrans_result](https://user-images.githubusercontent.com/47970756/77725193-c63ece00-702f-11ea-99df-a8bb6ec716be.png)

**Comment by acboyty** [comment]
I find changing the parameter 'pad'(used in cov2d function) to 'True' makes the input and output the same size.
![code](https://user-images.githubusercontent.com/47970756/77816495-fa80c000-70fd-11ea-8e0e-58620257d744.png)
So I think it a switch you designed, and I ignored it. Sorry for interruption.

**Comment by mgharbi** [comment]
Yes, that's right. You can enable/disable that switch to preserve only the valid area of the convolution.
