### ISSUE TITLE
dataset downloading error

### ISSUE THREAD

**Issue by zhaobinNF** [mgharbi/demosaicnet#7]
Hello, I am a student from China who is new in the JDD region.  Recently I want to download the MIT moire dataset but there is always an error when downloading. I would really appreciate it if you could help me solve the problem. Thank you very much.
![image](https://user-images.githubusercontent.com/72935067/112959910-7b8def80-9176-11eb-9e00-3daaa0436ef8.png)

Running curl -o datasets.z01 https://data.csail.mit.edu/graphics/demosaicnet/datasets.z01
Checksum: b'5b7bbc36172da06b7ce2883dcb456515' da46277afe85d3a91c065e4751fb8175
datasets.z01 MD5 incorrect, re-downloading.
https://data.csail.mit.edu/graphics/demo

**Comment by mgharbi** [comment]
Have you tried wget? I could not reproduce the issue, the downloaded file produces the right checksum for me.

**Comment by mgharbi** [comment]
Also make sure the download did not run into issue, the file should be ~256MB.

**Comment by zhaobinNF** [comment]
I have solved this using my own code without checking the MD5. Maybe there is something wrong.

**Comment by anguoyang** [comment]
@mgharbi sorry for asking after the issue closed, I tried with wget, it is fine(file size matched), but I could NOT find the filelist.txt in the val folder, is it correct?

**Comment by mgharbi** [comment]
I understand you managed to download the files without issue. If this is the case, you can regenerate the file list with the following command:

`find . -name "*.png" | grep val > val.txt` there should be 2,000 or 4,000 files in the generated list file (I don't recall which it is).

**Comment by anguoyang** [comment]
@mgharbi thank you so much, now it works
