### ISSUE TITLE
TypeError: ones_like(): argument 'input' (position1) must be Tensor, not Array

### ISSUE THREAD

**Issue by zuotengxu** [mgharbi/demosaicnet#8]
Hello
I am trying to run demosaicnet follow the readme file
after running 'python setup.py install' and 'demosaicnet_demo ./myoutputdir', I got following error:

'TypeError: ones_like(): grgument 'input' (position1) must be Tensor, not Array'

I have try to change my pytorch version to 1.4.0 or 1.8.0, by that don't help at all
how can I run this demo? 
thx

**Comment by mgharbi** [comment]
Thanks for finding this, this should be fixed with the latest update to "master". Make sure to uninstall the old version if you did "pip install": "pip uninstall demosaicnet"
