### ISSUE TITLE
confusing about the code

### ISSUE THREAD

**Issue by zhaobinNF** [mgharbi/demosaicnet#9]
![image](https://user-images.githubusercontent.com/72935067/115332675-e1482700-a1ca-11eb-8aa4-837e525d6c55.png)
I am wondering why here we multiply them.

**Comment by mgharbi** [comment]
The pretrained model we released had a slight variation on the network architecture with multiplicative feature interaction. This was inspired by earlier demosaicking algorithm that "selects" over interpolation direction. It is not needed to match the performance of the paper, a regular convolution layer works fine.
